package com.example.fishinggame

object Fishes {
    fun getFishes(): List<Fish> {
        val list: List<Fish> = listOf(
            Fish("Alligator Gar",
                "https://static.fishingbooker.com/public/images/fish/275x160/alligator-gar.png"),
            Fish("Amberjack",
                "https://static.fishingbooker.com/public/images/fish/275x160/amberjack.png"),
            Fish("Arapaima",
                "https://static.fishingbooker.com/public/images/fish/275x160/arapaima.png") ,
            Fish("Arctic Char",
                "https://static.fishingbooker.com/public/images/fish/275x160/arctic-char.png"),
            Fish("Asp",
                "https://static.fishingbooker.com/public/images/fish/275x160/asp.png"),
            Fish("Barracuda (Great)",
                "https://static.fishingbooker.com/public/images/fish/275x160/barracuda-great.png"),
       Fish("Barracuda (Pacific)",
           "https://static.fishingbooker.com/public/images/fish/275x160/barracuda-pacific.png"),
        Fish("Barramundi",
            "https://static.fishingbooker.com/public/images/fish/275x160/barramundi.png"),
        Fish("Bass (Australian)",
            "https://static.fishingbooker.com/public/images/fish/275x160/bass-australian.png"),
        Fish("Bass (Largemouth)",
            "https://static.fishingbooker.com/public/images/fish/275x160/bass-largemouth.png"),
        Fish("Bass (Peacock)",
            "https://static.fishingbooker.com/public/images/fish/275x160/bass-peacock.png"),
        Fish("Bass (Rainbow)",
            "https://static.fishingbooker.com/public/images/fish/275x160/bass-Rainbow.png"),
        Fish("Bass (Smallmouth)",
            "https://static.fishingbooker.com/public/images/fish/275x160/bass-smallmouth.png"),
        Fish("Bass (Spotted)",
            "https://static.fishingbooker.com/public/images/fish/275x160/bass-spotted.png"),
        Fish("Bass (Striped)",
            "https://static.fishingbooker.com/public/images/fish/275x160/bass-striped.png"),
        Fish("Bass (White)",
            "https://static.fishingbooker.com/public/images/fish/275x160/bass-white.png"),
        Fish("Black Drum",
            "https://static.fishingbooker.com/public/images/fish/275x160/black-drum.png"),
        Fish("Black Jewfish",
            "https://static.fishingbooker.com/public/images/fish/275x160/black-jewfish.png"),
            Fish("Black Rockfish",
                "https://static.fishingbooker.com/public/images/fish/275x160/black-rockfish.png"),
            Fish("Bluefish",
                "https://static.fishingbooker.com/public/images/fish/275x160/bluefish.png"),
            Fish("Bluenose Warehou",
                "https://static.fishingbooker.com/public/images/fish/275x160/bluenose-warehou.png"),
            Fish("Bohar Snapper",
                "https://static.fishingbooker.com/public/images/fish/275x160/bohar-snapper.png"),
Fish(        "Bonefish ",
    "https://static.fishingbooker.com/public/images/fish/275x160/bonefish.png"),
Fish(        "Bonito ",
    "https://static.fishingbooker.com/public/images/fish/275x160/bonito.png"),
Fish(        "Bowfin ",
    "https://static.fishingbooker.com/public/images/fish/275x160/bwfin.png"),
Fish(        "Bream (Black) ",
    "https://static.fishingbooker.com/public/images/fish/275x160/bream-black.png"),
Fish(        "Bream (Common) ",
    "https://static.fishingbooker.com/public/images/fish/275x160/bream-common.png"),
Fish(        "Bream (Fingermark) ",
    "https://static.fishingbooker.com/public/images/fish/275x160/bream-fingermark.png"),
Fish(        "Brook Trout ",
    "https://static.fishingbooker.com/public/images/fish/275x160/brook-trout.png"),
Fish(        "Brown Trout ",
    "https://static.fishingbooker.com/public/images/fish/275x160/brown-trout.png"),
     Fish(   "Bullhead ",
         "https://static.fishingbooker.com/public/images/fish/275x160/bullhead.png"),
Fish(        "Burbot ",
    "https://static.fishingbooker.com/public/images/fish/275x160/burbot.png"),
     Fish(   "Calico Bass ",
         "https://static.fishingbooker.com/public/images/fish/275x160/calico-bass.png"),
 Fish(       "California Corbina ",
     "https://static.fishingbooker.com/public/images/fish/275x160/california-corbina.png"),
      Fish(  "California Sheephead ",
          "https://static.fishingbooker.com/public/images/fish/275x160/california-sheephead.png"),
Fish(        "Carp ",
    "https://static.fishingbooker.com/public/images/fish/275x160/carp.png"),
     Fish(   "Catfish ",
         "https://static.fishingbooker.com/public/images/fish/275x160/catfish.png"),
 Fish(       "Cero Mackerel ",
     "https://static.fishingbooker.com/public/images/fish/275x160/cero-mackerel.png"),
      Fish(  "Clam ",
          "https://static.fishingbooker.com/public/images/fish/275x160/clam.png"),
Fish(        "Clown Knife Fish ",
    "https://static.fishingbooker.com/public/images/fish/275x160/clown-knife-fish.png"),
     Fish(   "Coalfish ",
         "https://static.fishingbooker.com/public/images/fish/275x160/coalfish.png"),
   Fish(     "Cobia ",
       "https://static.fishingbooker.com/public/images/fish/275x160/cobia.png"),
  Fish(      "Cod ",
      "https://static.fishingbooker.com/public/images/fish/275x160/cod.png"),
Fish(        "Cod (Blue) ",
    "https://static.fishingbooker.com/public/images/fish/275x160/cod-blue.png"),
     Fish(   "Cod (Breaksea) ",
         "https://static.fishingbooker.com/public/images/fish/275x160/cod-breaksea.png"),
   Fish(     "Common Ling ",
       "https://static.fishingbooker.com/public/images/fish/275x160/common-ling.png"),
Fish(        "Common Pandora ",
    "https://static.fishingbooker.com/public/images/fish/275x160/common-pandora.png"),
    Fish(    "Conger Eel ",
        "https://static.fishingbooker.com/public/images/fish/275x160/conger-eel.png"),
    Fish(    "Coral Trout ",
        "https://static.fishingbooker.com/public/images/fish/275x160/coral-trout.png"),
      Fish(  "Crab ",
          "https://static.fishingbooker.com/public/images/fish/275x160/crab.png"),
    Fish(    "Crappie ",
        "https://static.fishingbooker.com/public/images/fish/275x160/crappie.png"),
   Fish(     "Crayfish ",
       "https://static.fishingbooker.com/public/images/fish/275x160/crayfish.png"),
       Fish( "Cutthroat Trout ",
           "https://static.fishingbooker.com/public/images/fish/275x160/cutthroat-trout.png"),
  Fish(      "Dentex ",
      "https://static.fishingbooker.com/public/images/fish/275x160/dentex.png"),
   Fish(     "Dhufish ",
       "https://static.fishingbooker.com/public/images/fish/275x160/dhufish.png"),
    Fish(    "Dogfish ",
        "https://static.fishingbooker.com/public/images/fish/275x160/dogfish.png"),
    Fish(    "Dolly Varden ",
        "https://static.fishingbooker.com/public/images/fish/275x160/dolly-varden.png"),
    Fish(    "Dolphin (Mahi Mahi) ",
        "https://static.fishingbooker.com/public/images/fish/275x160/dolphin-mahi-mahi.png"),
   Fish(     "Flathead ",
       "https://static.fishingbooker.com/public/images/fish/275x160/flathead.png"),
    Fish(    "Flounder ",
        "https://static.fishingbooker.com/public/images/fish/275x160/flounder.png"),
    Fish(    "Freshwater Drum ",
        "https://static.fishingbooker.com/public/images/fish/275x160/freshwater-drum.png"),
    Fish(    "Garfish ",
        "https://static.fishingbooker.com/public/images/fish/275x160/garfish.png"),
   Fish(     "Geelbek (Cape Salmon) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/geelbek-cape-salmon).png"),
   Fish(     "Gilt-head (Seabream) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/gilt-head-seabream.png"),
   Fish(     "Golden Dorado ",
       "https://static.fishingbooker.com/public/images/fish/275x160/golden-dorado.png"),
   Fish(     "Grayling ",
       "https://static.fishingbooker.com/public/images/fish/275x160/grayling.png"),
   Fish(     "Grouper (Black) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/grouper-black.png"),
   Fish(     "Grouper (Broomtail) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/grouper-broomtail.png"),
   Fish(     "Grouper (Dusky) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/grouper-dusky.png"),
    Fish(    "Grouper (Gag) ",
        "https://static.fishingbooker.com/public/images/fish/275x160/grouper-gag.png"),
    Fish(    "Grouper (Goliath) ",
        "https://static.fishingbooker.com/public/images/fish/275x160/grouper-goliath.png"),
    Fish(    "Grouper (Hamour) ",
        "https://static.fishingbooker.com/public/images/fish/275x160/grouper-hamour.png"),
   Fish(     "Grouper (Red) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/grouper-red.png"),
   Fish(     "Grouper (Scamp) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/grouper-scamp.png"),
   Fish(     "Grouper (Snowy) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/grouper-snowy.png"),
   Fish(     "Grunt ",
       "https://static.fishingbooker.com/public/images/fish/275x160/grunt.png"),
   Fish(     "Grunter (Javelin) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/grunter-javelin.png"),
   Fish(     "Gurnard ",
       "https://static.fishingbooker.com/public/images/fish/275x160/gurnard.png"),
   Fish(     "Haddock ",
       "https://static.fishingbooker.com/public/images/fish/275x160/haddock.png"),
   Fish(     "Halibut ",
       "https://static.fishingbooker.com/public/images/fish/275x160/halibut.png"),
   Fish(     "Hapuka ",
       "https://static.fishingbooker.com/public/images/fish/275x160/hapuka.png"),
   Fish(     "Herring ",
       "https://static.fishingbooker.com/public/images/fish/275x160/herring.png"),
   Fish(     "Hogfish ",
       "https://static.fishingbooker.com/public/images/fish/275x160/hogfish.png"),
   Fish(     "Hybrid Striped Bass ",
       "https://static.fishingbooker.com/public/images/fish/275x160/hybrid-striped-bass.png"),
   Fish(     "Indian Threadfish ",
       "https://static.fishingbooker.com/public/images/fish/275x160/indian-threadfish.png"),
   Fish(     "Jack (African Pompano) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/jack-african-pompano.png"),
   Fish(     "Jack (Almaco) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/jack-almaco.png"),
   Fish(     "Jack (Horse-eye) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/jack-horse-eye.png"),
   Fish(     "Jack Crevalle ",
       "https://static.fishingbooker.com/public/images/fish/275x160/jack-crevalle.png"),
   Fish(     "Jobfish (Green) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/jobfish-green.png"),
    Fish(    "Jobfish (Rusty) ",
        "https://static.fishingbooker.com/public/images/fish/275x160/jobfish-rusty.png"),
    Fish(    "John Dory ",
        "https://static.fishingbooker.com/public/images/fish/275x160/john-dory.png"),
   Fish(     "Kahawai ",
       "https://static.fishingbooker.com/public/images/fish/275x160/bass-peacock.png"),
   Fish(     "King George Whiting ",
       "https://static.fishingbooker.com/public/images/fish/275x160/king-george-whiting.png"),
  Fish(      "King Mackerel (Kingfish) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/king-mackerel-kingfish.png"),
  Fish(      "Kob ",
      "https://static.fishingbooker.com/public/images/fish/275x160/kob.png"),
  Fish(      "Ladyfish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/ladyfish.png"),
  Fish(      "Lake Trout ",
      "https://static.fishingbooker.com/public/images/fish/275x160/lake-trout.png"),
  Fish(      "Leatherjacket ",
      "https://static.fishingbooker.com/public/images/fish/275x160/leatherjacket.png"),
  Fish(      "Leerfish (Garrick) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/leerfish-garrick.png"),
   Fish(     "Lingcod ",
       "https://static.fishingbooker.com/public/images/fish/275x160/lingcod.png"),
   Fish(     "Lionfish ",
       "https://static.fishingbooker.com/public/images/fish/275x160/lionfish.png"),
  Fish(      "Little Tunny (False Albacore) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/little-tunny-false-albacore.png"),
  Fish(      "Lobster ",
      "https://static.fishingbooker.com/public/images/fish/275x160/lobster.png"),
  Fish(      "Long-Tail Red Snapper (Onaga) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/long-tail-red-snapper-onaga.png"),
   Fish(     "Mackerel (Atlantic) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/mackerel-atlantic.png"),
   Fish(     "Marlin (Black) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/marlin-black.png"),
  Fish(      "Marlin (Blue) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/marlin-blue.png"),
  Fish(      "Marlin (Striped) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/marlin-striped.png"),
  Fish(      "Marlin (White) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/marlin-white.png"),
  Fish(      "Milkfish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/milkfish.png"),
  Fish(      "Morwong ",
      "https://static.fishingbooker.com/public/images/fish/275x160/morwong.png"),
  Fish(      "Murray Cod ",
      "https://static.fishingbooker.com/public/images/fish/275x160/murray-co.png"),
  Fish(      "Muskellunge (Musky) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/muskellunge-musky.png"),
 Fish(       "Musselcracker ",
     "https://static.fishingbooker.com/public/images/fish/275x160/musselcracker.png"),
  Fish(      "Nannygai ",
      "https://static.fishingbooker.com/public/images/fish/275x160/nannygai.png"),
  Fish(      "Needlefish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/needlefish.png"),
  Fish(      "Nursehound (Bull Huss) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/nursehound-bull-huss.png"),
  Fish(      "Paddlefish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/paddlefish.png"),
  Fish(      "Papuan Black Snapper ",
      "https://static.fishingbooker.com/public/images/fish/275x160/papuan-black-snapper.png"),
  Fish(      "Payara ",
      "https://static.fishingbooker.com/public/images/fish/275x160/bass-peacock.png"),
  Fish(      "Pearl Perch ",
      "https://static.fishingbooker.com/public/images/fish/275x160/pearl-perch.png"),
  Fish(      "Pejerrey (Silverside) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/pejerrey-silverside.png"),
  Fish(      "Perch (European) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/perch-european.png"),
  Fish(      "Perch (Golden) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/perch-golden.png"),
  Fish(      "Perch (Silver) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/perch-silver.png"),
  Fish(      "Perch (White) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/perch-white.png"),
  Fish(      "Perch (Yellow) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/perch-yellow.png"),
  Fish(      "Permit ",
      "https://static.fishingbooker.com/public/images/fish/275x160/permit.png"),
  Fish(      "Pike (Northern) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/pike-northern.png"),
  Fish(      "Pike Perch (Zander) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/pike-perch-zander.png"),
  Fish(      "Pink Maomao ",
      "https://static.fishingbooker.com/public/images/fish/275x160/pink-maomao.png"),
  Fish(      "Pollock ",
      "https://static.fishingbooker.com/public/images/fish/275x160/pollock.png"),
  Fish(      "Pompano ",
      "https://static.fishingbooker.com/public/images/fish/275x160/pompano.png"),
  Fish(      "Queen Snapper (Australian) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/queen-snapper-australian.png"),
  Fish(      "Queen Snapper (Caribbean) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/queen-snapper-caribbean.png"),
  Fish(      "Queenfish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/queenfish.png"),
  Fish(      "Queensland Groper (Giant Grouper) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/queensland-groper-giant-grouper.png"),
  Fish(      "Rainbow Runner ",
      "https://static.fishingbooker.com/public/images/fish/275x160/rainbow-runner.png"),
  Fish(      "Rainbow Trout (Steelhead) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/rainbow-trout-steelhead.png"),
  Fish(      "Ray ",
      "https://static.fishingbooker.com/public/images/fish/275x160/ray.png"),
  Fish(      "Redfish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/redfish.png"),
   Fish(     "Rockfish ",
       "https://static.fishingbooker.com/public/images/fish/275x160/rockfish.png"),
  Fish(      "Roosterfish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/roosterfish.png"),
   Fish(     "Sailfish ",
       "https://static.fishingbooker.com/public/images/fish/275x160/sailfish.png"),
  Fish(      "Salmon ",
      "https://static.fishingbooker.com/public/images/fish/275x160/salmon.png"),
  Fish(      "Salmon (Atlantic) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/salmon-atlantic.png"),
  Fish(      "Salmon (Australian) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/salmon-australian.png"),
  Fish(      "Salmon (Chinook) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/salmon-chinook.png"),
  Fish(      "Salmon (Chum) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/salmon-chum.png"),
  Fish(      "Salmon (Coho) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/salmon-coho.png"),
  Fish(      "Salmon (Pink) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/salmon-pink.png"),
  Fish(      "Salmon (Sockeye) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/salmon-sockeye.png"),
  Fish(      "Samson Fish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/samson-fish.png"),
   Fish(     "Sand Bass ",
       "https://static.fishingbooker.com/public/images/fish/275x160/sand-bass.png"),
  Fish(      "Saratoga ",
      "https://static.fishingbooker.com/public/images/fish/275x160/saratoga.png"),
 Fish(       "Sauger ",
     "https://static.fishingbooker.com/public/images/fish/275x160/sauger.png"),
 Fish(       "Scallop ",
     "https://static.fishingbooker.com/public/images/fish/275x160/scallop.png"),
  Fish(      "Scorpionfish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/scorpionfish.png"),
  Fish(      "Sculpin ",
      "https://static.fishingbooker.com/public/images/fish/275x160/sculpin.png"),
   Fish(     "Scup (Porgy) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/scup-porgy.png"),
  Fish(      "Seabass (Black) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/seabass-black.png"),
  Fish(      "Seabass (European) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/seabass-european.png"),
  Fish(      "Seabass (Giant) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/seabass-giant.png"),
   Fish(     "Seabass (White) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/seabass-white.png"),
   Fish(     "Shad ",
       "https://static.fishingbooker.com/public/images/fish/275x160/shad.png"),
  Fish(      "Shark (Blacktip) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/shark-blacktip.png"),
  Fish(      "Shark (Blue) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/shark-blue.png"),
  Fish(      "Shark (Bonnethead) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/shark-bonnethead.png"),
  Fish(      "Shark (Bull) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/shark-bull.png"),
  Fish(      "Shark (Greenland) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/shark-greenland.png"),
  Fish(      "Shark (Gummy) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/shark-gummy.png"),
   Fish(     "Shark (Hammerhead) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/shark-hammerhead.png"),
   Fish(     "Shark (Lemon) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/shark-lemon.png"),
  Fish(      "Shark (Leopard) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/shark-leopard.png"),
  Fish(      "Shark (Mako) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/shark-mako.png"),
  Fish(      "Shark (Nurse) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/shark-nurse.png"),
   Fish(     "Shark (Porbeagle) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/shark-porbeagle.png"),
  Fish(      "Shark (Thresher) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/shark-thresher.png"),
  Fish(      "Shark (Tiger) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/shark-tiger.png"),
  Fish(      "Shark (Tope) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/shark-tope.png"),
  Fish(      "Sheepshead ",
      "https://static.fishingbooker.com/public/images/fish/275x160/sheepshead.png"),
  Fish(      "Short-Tail Red Snapper (Ehu) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/short-tail-red-snapper-ehu.png"),
   Fish(     "Shrimp ",
       "https://static.fishingbooker.com/public/images/fish/275x160/shrimp.png"),
  Fish(      "Sierra Mackerel ",
      "https://static.fishingbooker.com/public/images/fish/275x160/sierra-mackerel.png"),
  Fish(      "Skate ",
      "https://static.fishingbooker.com/public/images/fish/275x160/skate.png"),
  Fish(      "Snakehead ",
      "https://static.fishingbooker.com/public/images/fish/275x160/snakehead.png"),
  Fish(      "Snapper (Cubera) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/snapper-cubera.png"),
  Fish(      "Snapper (Lane) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/snapper-lane.png"),
  Fish(      "Snapper (Mangrove) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/snapper-mangrove.png"),
  Fish(      "Snapper (Mullet) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/snapper-mullet.png"),
  Fish(      "Snapper (Mutton) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/snapper-mutton.png"),
  Fish(      "Snapper (Pink) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/snapper-pink.png"),
  Fish(      "Snapper (Red Emperor) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/snapper-red-emperor.png"),
  Fish(      "Snapper (Red) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/snapper-red.png"),
  Fish(      "Snapper (Vermilion) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/snapper-vermilion.png"),
  Fish(      "Snapper (Yellowtail) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/snapper-yellowtail.png"),
  Fish(      "Snoek ",
      "https://static.fishingbooker.com/public/images/fish/275x160/snoek.png"),
  Fish(      "Snook ",
      "https://static.fishingbooker.com/public/images/fish/275x160/snook.png"),
  Fish(      "Spadefish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/spadefish.png"),
  Fish(      "Spangled Emperor ",
      "https://static.fishingbooker.com/public/images/fish/275x160/spangled-emperor.png"),
  Fish(      "Spanish Mackerel ",
      "https://static.fishingbooker.com/public/images/fish/275x160/spanish-mackerel.png"),
  Fish(      "Spanish Mackerel (Narrow-barred) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/spanish-mackerel-narrow-barred.png"),
  Fish(      "Spearfish (Longbill) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/spearfish-longbill.png"),
  Fish(      "Spearfish (Shortbill) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/spearfish-shortbill.png"),
  Fish(      "Speckled Trout ",
      "https://static.fishingbooker.com/public/images/fish/275x160/speckled-trout.png"),
  Fish(      "Spotted Seatrout ",
      "https://static.fishingbooker.com/public/images/fish/275x160/spotted-seatrout.png"),
  Fish(      "Squid ",
      "https://static.fishingbooker.com/public/images/fish/275x160/squid.png"),
   Fish(     "Sturgeon ",
       "https://static.fishingbooker.com/public/images/fish/275x160/sturgeon.png"),
  Fish(      "Sunfish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/sunfish.png"),
   Fish(     "Sweetlip Emperor ",
       "https://static.fishingbooker.com/public/images/fish/275x160/sweetlip-emperor.png"),
  Fish(      "Swordfish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/swordfish.png"),
  Fish(      "Tailor ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tailor.png"),
  Fish(      "Tarakihi ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tarakihi.png"),
  Fish(      "Tarpon ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tarpon.png"),
  Fish(      "Tautog ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tautog.png"),
  Fish(      "Threadfin Salmon ",
      "https://static.fishingbooker.com/public/images/fish/275x160/threadfin-salmon.png"),
  Fish(      "Tigerfish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tigerfish.png"),
  Fish(      "Tigerfish (Goliath) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tigerfish-goliath.png"),
  Fish(      "Tilapia ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tilapia.png"),
  Fish(      "Tilefish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tilefish.png"),
  Fish(      "Trevally (Bigeye) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/trevally-bigeye.png"),
  Fish(      "Trevally (Blacktip) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/trevally-blacktip.png"),
  Fish(      "Trevally (Bluefin) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/trevally-bluefin.png"),
   Fish(     "Trevally (Giant) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/trevally-giant.png"),
   Fish(     "Trevally (Golden) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/trevally-golden.png"),
  Fish(      "Trevally (Silver) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/trevally-silver.png"),
  Fish(      "Triggerfish (Gray) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/triggerfish-gray.png"),
  Fish(      "Tripletail ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tripletail.png"),
  Fish(      "Trumpeter (Striped) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/trumpeter-striped.png"),
   Fish(     "Tuna (Albacore) ",
       "https://static.fishingbooker.com/public/images/fish/275x160/tuna-albacore.png"),
  Fish(      "Tuna (Bigeye) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tuna-bigeye.png"),
  Fish(      "Tuna (Blackfin) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tuna-blackfin.png"),
  Fish(      "Tuna (Bluefin) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tuna-bluefin.png"),
  Fish(      "Tuna (Dogtooth) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tuna-dogtooth.png"),
  Fish(      "Tuna (Longtail) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tuna-longtail.png"),
  Fish(      "Tuna (Skipjack) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tuna-skipjack.png"),
  Fish(      "Tuna (Yellowfin) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/tuna-yellowfin.png"),
  Fish(      "Wahoo ",
      "https://static.fishingbooker.com/public/images/fish/275x160/wahoo.png"),
  Fish(      "Walleye ",
      "https://static.fishingbooker.com/public/images/fish/275x160/walleye.png"),
  Fish(      "Weakfish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/weakfish.png"),
  Fish(      "Whitefish (Lake) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/whitefish-lake.png"),
  Fish(      "Whiting ",
      "https://static.fishingbooker.com/public/images/fish/275x160/whiting.png"),
  Fish(      "Wolffish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/wolffish.png"),
  Fish(      "Wrasse (Bluethroat) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/wrasse-bluethroat.png"),
  Fish(      "Wrasse (Humphead) ",
      "https://static.fishingbooker.com/public/images/fish/275x160/wrasse-humphead.png"),
  Fish(      "Yellowfish ",
      "https://static.fishingbooker.com/public/images/fish/275x160/yellowfish.png"),
  Fish(      "Yellowtail Amberjack ",
      "https://static.fishingbooker.com/public/images/fish/275x160/yellowtail-amberjack.png")
        )
        return list
    }
}